name: Trigger auto deployment for entaaichatapp-h2pw7-ca

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/entaaichatapp-h2pw7-ca-AutoDeployTrigger-0ee04c80-83de-4704-9f12-105d277b1a67.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ENTAAICHATAPPH2PW7CA_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ENTAAICHATAPPH2PW7CA_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ENTAAICHATAPPH2PW7CA_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: entrachatappgxx3ap6gzrskeregistry.azurecr.io
          registryUsername: ${{ secrets.ENTAAICHATAPPH2PW7CA_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ENTAAICHATAPPH2PW7CA_REGISTRY_PASSWORD }}
          containerAppName: entaaichatapp-h2pw7-ca
          resourceGroup: entaaichatapp-rg
          imageToBuild: entrachatappgxx3ap6gzrskeregistry.azurecr.io/entaaichatapp-h2pw7-ca:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


